name: gfas_scripts_dev
channels:
      - defaults
      - conda-forge
dependencies:
      - python=3.12
      - black
      - cdsapi
      - ipython
      - mypy
      - netcdf4
      - numpy
      - paramiko
      - pip
      - pylint
