name: gfas_scripts
channels:
      - defaults
      - conda-forge
dependencies:
      - python=3.7
      - cython
      - numpy
      - netcdf4
      - paramiko
      - pip
      - pip:
          - ecmwf-api-client
